version: '3'
services:
  kong-database:
    restart: on-failure
    image: cassandra
    container_name: kong-database
    volumes:
      - ./db:/var/lib/cassandra
    ports:
      - '9042:9042'
  kong:
    restart: on-failure
    image: kong
    container_name: kong
    links:
      - kong-database:kong-database
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8443:8443'
      - '7946:7946'
      - '7946:7946/udp'
